[package]
name = "stacks-signer-api"
version = "0.1.0"
edition = "2021"

[dependencies]
blockstack-core.workspace = true
clap.workspace = true
hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded = "0.7"
sqlx = { version = "0.5", features = ["sqlite", "runtime-tokio-native-tls"] }
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa = "3.3.0"
utoipa-swagger-ui = { version = "3.1.3" }
warp = "0.3.5"

[dev-dependencies]
ntest = "0.9.0"